# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-09-04 16:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogpost',
            name='url',
            field=models.CharField(max_length=100, primary_key=True, serialize=False),
        ),
    ]
