# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-06-21 02:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_blogpost_color'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogpost',
            name='link_text',
            field=models.CharField(default='', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='blogpost',
            name='link_url',
            field=models.CharField(default='', max_length=100),
            preserve_default=False,
        ),
    ]
