# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-06-21 03:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_auto_20170621_0212'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogpost',
            name='link_text',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='blogpost',
            name='link_url',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
